############################
#  Red Studio Development  #
#      by: Nikonbite       #
############################


# Настройки
WORLD:
  # Точка спавна - /setspawn
  SPAWN: world, 0, 100, 0, 0, 0
  # Выключить установку блоков
  DISABLE_BLOCK_PLACE: true
  # Выключить ломание блоков
  DISABLE_BLOCK_BREAK: true
  # Всегда день
  ALWAYS_DAY: true
  # Выключить мобов
  DISABLE_MOBS: true
  # Выключить урон для игроков
  DISABLE_DAMAGE: true
  # Выключить голод для игроков
  DISABLE_FOOD_CHANGE: true
  # Миры на которые действуют установленные правила
  ENABLED_WORLDS:
    - "world"


# Jump Pad привязан к блоку слизи,
# и изменить его не получится.
# В дальнейших обновлениях я это добавлю

PAD:
  MULTIPLIER_X: 3.5
  MULTIPLIER_Y: 0.8



# Локализация
PREFIX:                "§c§lLobby §7:: §f"

COMMON:
  NO_PERMS:            "У вас нет прав для выполнения этой команды!"
  PLAYER_OFFLINE:      "Игрок не в сети."

JOIN_MESSAGES:
  DEFAULT:              "§e▸ §fИгрок §e%s§f зашёл на проект! §e◂"
  MOTD:
    - "§c§lExample Network"
    - ""
    - "§fТут что-то можно написать, но я не придумал."

COMMANDS:
  SETSPAWN_SUCCESS:     "Вы успешно установили точку спавна игроков."
  SPAWN_SUCCESS:        "Вы успешно телепортировались на точку спавна"
  SPAWN_SUCCESS_PLAYER: "Вы успешно телепортировали игрока %s на точку спавна"
  SPAWN_SUCCESS_TARGET: "Вы были телепортированы на точку спавна игроком &c%s&f."

  HEAL_SUCCESS:         "Вы успешно себя вылечили."
  HEAL_SUCCESS_PLAYER:  "Вы успешно вылечили игрока &c%s&f."
  HEAL_SUCCESS_TARGET:  "Вас вылечил игрок &c%s&f."

  GMS_SUCCESS:          "Ваш текущий режим игры: §aВыживание§f."
  GMS_SUCCESS_PLAYER:   "Игроку &c%s&f установлен режим игры: §aВыживание§f."
  GMS_SUCCESS_TARGET:   "Игрок &c%s&f установил вам режим игры: §aВыживание§f."

  GMC_SUCCESS:          "Ваш текущий режим игры: §dКреатив§f."
  GMC_SUCCESS_PLAYER:   "Игроку &c%s&f установлен режим игры: §dКреатив§f."
  GMC_SUCCESS_TARGET:   "Игрок &c%s&f установил вам режим игры: §dКреатив§f."

  GMA_SUCCESS:          "Ваш текущий режим игры: §eПриключение§f."
  GMA_SUCCESS_PLAYER:   "Игроку &c%s&f установлен режим игры: §eПриключение§f."
  GMA_SUCCESS_TARGET:   "Игрок &c%s&f установил вам режим игры: §eПриключение§f."

  GMSP_SUCCESS:         "Ваш текущий режим игры: §7Наблюдатель§f."
  GMSP_SUCCESS_PLAYER:  "Игроку &c%s&f установлен режим игры: §7Наблюдатель§f."
  GMSP_SUCCESS_TARGET:  "Игрок &c%s&f установил вам режим игры: 7Наблюдатель§f."

  GM_ALREADY:           "У вас уже установлен этот режим игры!"
  GM_HELP:              "Используй: §c/gm <0/1/2/3> (игрок)"

  FLY_SUCCESS:          "Вы установили режим полёта на: "
  FLY_SUCCESS_PLAYER:   "Вы установили режим полёта для игрока &c%s&f на: "
  FLY_SUCCESS_TARGET:   "Игрок &c%s&f установил статус вашего полёта на: "

  REDLOBBY_RELOADED:    "Конфигурация успешно перезагружена!"
  REDLOBBY_HELP:
    - "§7§m============================================="
    - "§7"
    - "§fСписок команд плагина§f:"
    - " §8- §c/gmsp (игрок) §7▸ §fРежим игры Наблюдатель"
    - " §8- §c/gma (игрок) §7▸ §fРежим игры Приключение"
    - " §8- §c/gms (игрок) §7▸ §fРежим игры Выживание"
    - " §8- §c/gmc (игрок) §7▸ §fРежим игры Креатив"
    - " §8- §c/fly (игрок) §7▸ §fВключить полёт"
    - " §8- §c/heal (игрок) §7▸ §fВылечиться"
    - " §8- §c/setspawn §7▸ §fУстановить точку спавна"
    - " §8- §c/spawn (игрок) §7▸ §fТелепортироваться на спавн"
    - " §8- §c/gmc <0/1/2/3> (игрок) §7▸ §fРежим игры"
    - " §8- §c/redlobby reload §7▸ §fПерезагрузить конфиг"
    - "§7"
    - "§7§m============================================="

# Не обращайте внимания, тестовая тема...
MENUS:
  SLOT1_NAME: "§fСервер §7:: §c§lLobby"
  SLOT1_LORE:
    - ""
    - "§fЭта кнопочка телепортирует"
    - "§fвас в лобби"
    - "§7"
    - "§7▸ Нажмите, чтобы присоединиться"
    -
  SLOT1: "Не пукни :)"